//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailAccount
    {
        public int MailAccountId { get; set; }
        public int MailBoxId { get; set; }
        public string AccountName { get; set; }
        public string Forwarding { get; set; }
        public int MaxSizeMB { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Status { get; set; }
    
        public virtual MailBox MailBox { get; set; }
    }
}
