//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailAliasName
    {
        public int MailAliasNameId { get; set; }
        public int MailBoxId { get; set; }
        public string AliasName { get; set; }
    
        public virtual MailBox MailBox { get; set; }
    }
}
